### ISSUE TITLE
Правила построения классов

### ISSUE THREAD

**Issue by semyondragunov** [SL7/Procyon#1]
Есть 2 вариант построения классов:

1) class=table-red или .table-green и т.д.
При этом будут выполняться 2 селектора: [class*="table-"] {Общие правила} и .table-red {Дизайн}

2) class=table red
То есть раздельно. Тоже 2 селектора по аналогии: .table и .table.red

Ещё вопрос: я использую классы типа .open и .active в нужных элементах, вместо скажем отдельных .tabs-open и .tabs-active. Делаю это для уменьшения кол-ва классов которые необходимо помнить. Как идея?

**Comment by semyondragunov** [comment]
Оставляю вариант 2. Так как примеси в препроцессорах можно всегда сделать.

Дополнительный вопрос: Оставляю одинаковые классы, работа по селекторам будет происходить по принципу компонентов.

Подробнее по работе с классами на офф. сайте фреймфорка.

Стандарты кодинга - https://github.com/SL7/CodingStandards

**Comment by EmperorSAM** [comment]
Стандарты кодинга - https://github.com/SL7/CodingStandards
