### ISSUE TITLE
Нужна документация для Drupal

### ISSUE THREAD

**Issue by GDI123** [SL7/Procyon#10]
Нужна документация по фреймворку для Drupal
1. Как установить демонстрационную тему и как привязать к ней фреймворк
2. Как сделать простейший сайт, например, воспроизвести демо Procyon  на своем сайте.

Понятно, что зубрам Drupal это не нужно, собственно, им и сам Процион не сильно и нужен. Но это очень нужно новичкам.

**Comment by semyondragunov** [comment]
1. В шаблоне https://github.com/EmperorSAM/ProcyonTheme есть папки less, css и js. В папку less ложатся файлы, если вы разрабатываете на препроцессоре через спец. модуль. В css же ложится готовая кастомная компиляция или дефолтный файл из css папки в фреймворке (на выбор минимальная или полная версия). В папку js копируются файлы из одноимённой папки в фреймворке.
   Затем в procyon.info или *.info файле сабтемы подключаете их как обычно (или less или css). В procyon.info есть пример. И скиньте кеш.
2. Тут наверное Вы имеете ввиду уроки по созданию? Так как вся документация есть на официальном сайте.

Сначала будет принято решение по самому Procyon, и если разработка будет продолжена, то появятся и уроки.

**Comment by GDI123** [comment]
Да, с первым уже разобрался. Но, обычно, такое, все же, пишут хотя бы в README.md.

И да, нужны уроки. Вот не нашел вменяемых инструкций, как конкретно делать одностраничные сайты на Drupal, ни на английском, ни на русском языках, особенно с использованием CSS фреймворков.
Под документацией Вы имеете в виду описание стилей на официальном сайте? Мне как новичку не понятно, как потом скрестить хтмл-дизайн, что сделан на фреймворке и Drupal. Я смотрю, у Вас очень чистый css в исходнике страницы. Опишите, пожалуйста, как вы это сделали. Понятно, что написать какой то абстрактный урок трудно. Но если будет инструкция, как воспроизвести самому Ваш официальный сайт, это снимет большинство вопросов. Ведь на сайте как раз и используются все элементы фреймворка.

**Comment by semyondragunov** [comment]
На официальном сайте в основном использовалась стандартная разметка фреймворка.
Дальнейшая верстка происходила дополнением кода в less или css (в зависимости как вы разрабатываете).
Советую фреймворк использовать как готовое решение и не изменять там код, а дописывать его отдельно.

**Comment by GDI123** [comment]
В том и вопрос "Как его использовать?". Я установил тему и фреймворк в соответствующие папки темы. Раскомментировал в .info файле темы пути у этим папкам. Включил тему.
Что делать дальше? Как сделать такое же меню, какой модуль для меню использовать (void menu)? И главный вопрос для меня. Как сделать контент на одной странице? Блоками, Панелями, как конкретно?

**Comment by semyondragunov** [comment]
Использовать просто, вставляете код (как в документации) и он преобразуется в нужный элемент.
Отдельных модулей для меню, спойлеров и т.д. ещё не делалось. Так что вставлять только вручную.
В смысле контент на одной странице? Для разметки в фреймворке есть **Grid**, получаются адаптивные блоки. А если Вы имеете ввиду друпаловские Panels и т.д., то это к фреймворку не относится, хотя его можно встроить и туда.

Так как фреймворк использует препроцессор, то Вы можете запросто примешивать стандартные классы в любые другие.
