### ISSUE TITLE
procyon.js Uncaught TypeError

### ISSUE THREAD

**Issue by tgww** [SL7/Procyon#11]
$('.tabs:not(.collapsible)').each(function() {
        li_first = $(this).children('ul').find('li:first');
стр.43       li_first_a_id = li_first.children('a').attr('href').replace('#', '');   -----> Uncaught TypeError: Cannot read property 'replace' of undefined

**Comment by rekkaru** [comment]
упс, не туда

**Comment by semyondragunov** [comment]
Какая версия jquery?

**Comment by tgww** [comment]
1.10
Выше 1.5 вылазит

**Comment by semyondragunov** [comment]
Не могу воспроизвести ошибку. Ветка master (то есть beta 1)? Так-то код с **beta 1** ещё не обновлялся и такого быть не должно. Попробуйте чистую **beta 1** поставить и посмотреть, будет ли такая же ошибка.

Стандартная версия jquery для этого релиза 1.7

**Comment by semyondragunov** [comment]
Истечение времени вопроса.
