### ISSUE TITLE
Compile less

### ISSUE THREAD

**Issue by tgww** [SL7/Procyon#8]
[Compile]
..procyon.less -> ..\procyon.css

Expected ')' but found ' ' on line 423 in file 'procyon.grid.less':
[422]:  
[423]:     .to-generate-columns-fix(@n, (@i + 1));
       -------------------------------------^

[Done - Failed]
[Finished in 0.4s]

**Comment by semyondragunov** [comment]
Какой версии less компилятор? Ветка master?
Так как всё должно нормально компилироваться.

**Comment by tgww** [comment]
Да, извини, ошибка компилятора.
Бета 2 будет?)

**Comment by semyondragunov** [comment]
В скором времени решится дальнейшая судьба проекта. Будет оповещение.
