### ISSUE TITLE
Ошибка в описании отступов (offset)

### ISSUE THREAD

**Issue by tgww** [SL7/Procyon#9]
Привет! Ошибка в описании отступов на http://procyon.sl-7.ru/.
"Класс .xs-2-offset означает, что блок сделает отступ на 2 блока вправо для смартфонов и выше."
"<div>
    <div class="xs-12">.xs-12</div>
    <div class="xs-10 xs-2-offset">.xs-10 .xs-2-offset</div>
</div>"

В примере верно: .xs-offset-2

**Comment by semyondragunov** [comment]
Спасибо. Исправлено и на сайте и в ветке master.
